# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiraftstores.multiraft.atomix.io
spec:
  group: multiraft.atomix.io
  scope: Namespaced
  names:
    kind: MultiRaftStore
    listKind: MultiRaftStoreList
    plural: multiraftstores
    singular: multiraftstore
    shortNames:
      - cs
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              properties:
                cluster:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                partitions:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  nullable: true
                replicationFactor:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  default: 1
                heartbeatPeriod:
                  type: string
                electionTimeout:
                  type: string
                snapshotEntryThreshold:
                  type: integer
                  minimum: 1
                  nullable: true
                compactionRetainEntries:
                  type: integer
                  minimum: 0
                  nullable: true
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
      additionalPrinterColumns:
        - name: Status
          type: string
          description: The store state
          jsonPath: .status.state