apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftmembers.multiraft.atomix.io
spec:
  group: multiraft.atomix.io
  names:
    kind: RaftMember
    listKind: RaftMemberList
    plural: raftmembers
    singular: raftmember
    shortNames:
      - rm
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - cluster
                - shardID
                - memberID
                - replicaID
                - pod
                - type
                - config
              properties:
                cluster:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                shardID:
                  type: integer
                  minimum: 1
                memberID:
                  type: integer
                  minimum: 1
                  maximum: 1024
                replicaID:
                  type: integer
                  minimum: 1
                pod:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                type:
                  type: string
                  default: Member
                  enum:
                    - Member
                    - Observer
                    - Witness
                config:
                  type: object
                  required:
                    - peers
                  properties:
                    electionRTT:
                      type: integer
                      nullable: true
                    heartbeatRTT:
                      type: integer
                      nullable: true
                    snapshotEntries:
                      type: integer
                      nullable: true
                    compactionOverhead:
                      type: integer
                      nullable: true
                    maxInMemLogSize:
                      type: string
                      nullable: true
                    peers:
                      type: array
                      items:
                        type: object
                        required:
                          - pod
                          - memberID
                          - replicaID
                        properties:
                          pod:
                            type: object
                            required:
                              - name
                            properties:
                              name:
                                type: string
                          memberID:
                            type: integer
                            minimum: 1
                            maximum: 1024
                          replicaID:
                            type: integer
                            minimum: 1
                bootstrapPolicy:
                  type: string
                  enum:
                    - Bootstrap
                    - Join
            status:
              type: object
              properties:
                podRef:
                  type: object
                  required:
                    - name
                    - uid
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
                version:
                  type: integer
                  nullable: true
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                role:
                  type: string
                  enum:
                    - Follower
                    - Candidate
                    - Leader
                term:
                  type: integer
                  nullable: true
                leader:
                  type: integer
                  nullable: true
                lastUpdated:
                  type: string
                  format: date-time
                lastSnapshotIndex:
                  type: integer
                  nullable: true
                lastSnapshotTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: MemberID
          type: integer
          description: The identifier of the memember
          jsonPath: .spec.memberID
        - name: ReplicaID
          type: integer
          description: The identifier of the Raft replica associated with the member
          jsonPath: .spec.replicaID
        - name: ShardID
          type: integer
          description: The shard to which the member belongs
          jsonPath: .spec.shardID
        - name: Pod
          type: string
          description: The pod to which the member belongs
          jsonPath: .spec.pod.name
        - name: Type
          type: string
          description: The member type
          jsonPath: .spec.type
        - name: Role
          type: string
          description: The member role
          jsonPath: .status.role
        - name: Leader
          type: integer
          description: The current leader on the member
          jsonPath: .status.leader
        - name: Term
          type: integer
          description: The current term on the member
          jsonPath: .status.term
        - name: Snapshot Index
          type: integer
          description: The index at which the member last took a snapshot
          jsonPath: .status.lastSnapshotIndex
        - name: Snapshot Time
          type: string
          description: The last time the member took a snapshot
          jsonPath: .status.lastSnapshotTime
        - name: Status
          type: string
          description: The member state
          jsonPath: .status.state