# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

image:
  registry: ""
  repository: atomix/consensus-controller
  tag: v0.7.1
  pullPolicy: ""
  pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/runtime-controller-init
    tag: v0.7.7
    pullPolicy: Always
    pullSecrets: []

node:
  image:
    registry: ""
    repository: atomix/consensus-node
    tag: v0.13
    pullPolicy: ""
    pullSecrets: []
