# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "atomix-consensus-controller.fullname" . }}
webhooks:
  - name: validator.raftgroups.consensus.atomix.io
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system"]
    rules:
      - operations: ["CREATE"]
        apiGroups: ["multiraft.atomix.io"]
        apiVersions: ["v1beta2"]
        resources: ["raftgroups"]
        scope: Namespaced
    clientConfig:
      service:
        name: {{ template "atomix-consensus-controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-raft-group
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
  - name: validator.raftmembers.consensus.atomix.io
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system"]
    rules:
      - operations: ["CREATE"]
        apiGroups: ["multiraft.atomix.io"]
        apiVersions: ["v1beta2"]
        resources: ["raftmembers"]
        scope: Namespaced
    clientConfig:
      service:
        name: {{ template "atomix-consensus-controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-raft-member
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10