# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "atomix-multi-raft-controller.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ template "atomix-multi-raft-controller.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "atomix-multi-raft-controller.fullname" . }}
    spec:
      serviceAccountName: {{ template "atomix-multi-raft-controller.fullname" . }}
      initContainers:
      - name: init-certs
        image: {{ include "atomix-multi-raft-controller.imagename" .Values.init.image | quote }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        env:
        - name: CONTROLLER_NAME
          value: {{ template "atomix-multi-raft-controller.fullname" . }}
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /etc/atomix/config
          readOnly: true
        - name: certs
          mountPath: /etc/webhook/certs
      containers:
      - name: atomix-multi-raft-controller
        image: {{ include "atomix-multi-raft-controller.imagename" .Values.controller.image | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 443
          name: webhook-server
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/atomix-multi-raft-controller-ready
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        env:
        - name: CONTROLLER_NAME
          value: {{ template "atomix-multi-raft-controller.fullname" . }}
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROXY_IMAGE
          value: {{ include "atomix-multi-raft-controller.imagename" .Values.proxy.image | quote }}
        - name: RUNTIME_VERSION
          value: {{ .Values.proxy.runtimeVersion }}
        volumeMounts:
        - name: certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        - name: config
          mountPath: /etc/atomix/config
          readOnly: true
      volumes:
      - name: certs
        emptyDir: {}
      - name: config
        configMap:
          name: {{ template "atomix-multi-raft-controller.fullname" . }}-config