apiVersion: atomix.io/v3beta1
kind: Profile
metadata:
  name: example-profile
  namespace: default
spec:
  bindings:
    - name: consistent
      store:
        namespace: default
        name: example-multi-raft-store
      primitives:
        - kinds:
            - Map
          apiVersions:
            - v1
          names:
            - '*'
          tags:
            foo: bar
            bar: baz
