apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: example-profile
spec:
  bindings:
    - store:
        name: example-multi-raft-store
      selector:
        foo: bar
        bar: baz
      services:
        - name: atomix.runtime.map.v1.Map
          config:
            cache:
              enabled: true
