apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiraftnodes.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: MultiRaftNode
    listKind: MultiRaftNodeList
    plural: multiraftnodes
    singular: multiraftnode
  scope: Namespaced
  versions:
    - name: v2beta2
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - cluster
                - nodeID
              properties:
                cluster:
                  type: string
                nodeID:
                  type: integer
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
      additionalPrinterColumns:
        - name: Cluster
          type: string
          description: The cluster to which the member belongs
          jsonPath: .spec.cluster
        - name: Node
          type: integer
          description: The node to which the member belongs
          jsonPath: .spec.nodeID
        - name: Status
          type: string
          description: The Raft cluster state
          jsonPath: .status.state