apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftgroups.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftGroup
    listKind: RaftGroupList
    plural: raftgroups
    singular: raftgroup
  scope: Namespaced
  versions:
    - name: v2beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - cluster
                - groupID
              properties:
                cluster:
                  type: string
                groupID:
                  type: integer
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      required:
                        - nodeID
                      nodeID:
                        type: string
                      type:
                        type: string
                        default: Member
                        enum:
                          - Member
                          - Observer
                          - Witness
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                leader:
                  type: string
                term:
                  type: integer
      additionalPrinterColumns:
        - name: Cluster
          type: string
          description: The cluster to which the member belongs
          jsonPath: .spec.cluster
        - name: Group
          type: integer
          description: The group to which the member belongs
          jsonPath: .spec.groupID
        - name: Leader
          type: string
          description: The current leader for the partition
          jsonPath: .status.leader
        - name: Term
          type: integer
          description: The current term for the partition
          jsonPath: .status.term
        - name: Status
          type: string
          description: The partition state
          jsonPath: .status.state