apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftmembers.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftMember
    listKind: RaftMemberList
    plural: raftmembers
    singular: raftmember
  scope: Namespaced
  versions:
    - name: v2beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - cluster
                - groupID
                - nodeID
              properties:
                cluster:
                  type: string
                groupID:
                  type: integer
                nodeID:
                  type: integer
                type:
                  type: string
                  default: Member
                  enum:
                    - Member
                    - Observer
                    - Witness
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                role:
                  type: string
                leader:
                  type: string
                term:
                  type: integer
                index:
                  type: integer
                lastUpdated:
                  type: string
                  format: date-time
                lastSnapshotIndex:
                  type: integer
                lastSnapshotTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Cluster
          type: string
          description: The cluster to which the member belongs
          jsonPath: .spec.cluster
        - name: Node
          type: integer
          description: The node to which the member belongs
          jsonPath: .spec.nodeID
        - name: Group
          type: integer
          description: The group to which the member belongs
          jsonPath: .spec.groupID
        - name: Type
          type: integer
          description: The member type
          jsonPath: .spec.type
        - name: Role
          type: string
          description: The member role
          jsonPath: .status.role
        - name: Leader
          type: string
          description: The current leader on the member
          jsonPath: .status.leader
        - name: Term
          type: integer
          description: The current term on the member
          jsonPath: .status.term
        - name: Snapshot Index
          type: integer
          description: The index at which the member last took a snapshot
          jsonPath: .status.lastSnapshotIndex
        - name: Snapshot Time
          type: string
          description: The last time the member took a snapshot
          jsonPath: .status.lastSnapshotTime
        - name: Status
          type: string
          description: The member state
          jsonPath: .status.state